# Site settings
title: Don's blog
SEOTitle: 冉东的博客 | Donnie blog
header-img: img/book.jpg
email: randongchn@gmail.com
description: "关于嵌入式linux, 汽车电子 | 冉东， Embedded sofrware Engineer，| 这里是 @Don冉东 的个人博客，与你一起发现更大的世界。"
keyword: "冉东, Don, don, donnie, donnie blog, 冉东的博客,  博客, 个人网站, 嵌入式, linux, 车联网，嵌入式，汽车电子"
url: auto                               # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     donnie2016
zhihu_username:     donnie2016
github_username:    donnieran
#twitter_username:  donnie2016
#facebook_username: donnie2016



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

#Duoshuo settings
duoshuo_username: donnie2016
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: ture                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4b81008513e532dddf11994c94fbb8f5
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "从事嵌入式软件开发工作，对linux有浓厚兴趣，关注新技术。"
sidebar-avatar: /img/portrait-donnie.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: ture                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    }
]
